### ISSUE TITLE
Navigation's 'active' class not always applied

### ISSUE THREAD

**Issue by BrendonKoz** [Daniel-KM/omeka-bootstrap#1]
First off, this theme's completeness is awesome. Thanks for the updates to the original fork!

I'm currently trying to look into why the 'active' class does not always seem to show up for menu items after navigating to pages within that section.

Example (intention: "Browse Collections" always active):
Browse Collections: http://example.com/collections/browse (ACTIVE applied)
Collection 1: http://example.com/collections/show/1 (NOT active)

Is this intentional for the theme? If not, and I can find/fix some of it, I will supply a patch. Helpful hints on where to look are always nice. :)

I see there's a NavigationMenu.php file in the theme's Twitter/Partial folder which may handle something of this nature, but due to its file location am assuming it is Twitter specific?

**Comment by Daniel-KM** [comment]
Thanks.

Some code is needed to bypass the default Omeka decorators, so that's why I use a library for Twitter. All this library is a copy of the Omeka files, with some little changes. I probably forgot to set the active status, because I didn't need it. In fact, I use this theme in a site where the navigation menu is totally different (flat and without sub levels), so I didn't check the active status, so this is fine to fix it.

**Comment by BrendonKoz** [comment]
Sorry for the long delay! This is apparently how Omeka's navigation's active class assigning works. "Browse Collections" directly links to "/collections/browse" and any URL path that begins with this will belong to that navigational item. As soon as the navigation changes to "/collections/show" it's no longer under the "browse" URL hierarchy.

Thankfully the way I have my version of your theme configured, "/collections" defaults to the "/collections/browse" view without needing the specific end-url parameter. Likewise my "/items/browse" can also simply be "/items".

Although I have to disable the included and default Omeka navigation items of "Browse Collections" and "Browse Items" to replace them with custom URLs ("/collections" and "/items" respectively, using the same verbiage), this fixes the "active" class issue in a non-programmatic way (and is much easier). It was also what was suggested by John Flatness of the Omeka team.

https://forum.omeka.org/t/navigation-and-subpages-of-collections-or-items-and-isactive-css/3551
