### ISSUE TITLE
$googleAccount pro $account?

### ISSUE THREAD

**Issue by AlecWK** [Daniel-KM/omeka-bootstrap#3]
Hi Daniel, 
in https://github.com/Daniel-KM/Omeka-theme-Bootstrap/blob/3d37d482dcdd8d1afdf5936d289d95db96aa8e38/common/analyticstracking.php#L7
$googleAccount should be $account?
cfr. https://github.com/Daniel-KM/Omeka-theme-Bootstrap/blob/3d37d482dcdd8d1afdf5936d289d95db96aa8e38/common/footer.php#L61
best,
Alec

**Comment by Daniel-KM** [comment]
Thanks for your report. 
I don't have google account, so it is an old code that was stay in place since a long time.
There is an issue in the footer. I'm pushing this code.
```php
<?php echo common('analyticstracking.php', array('googleAccount' => $googleAccount)); ?> 
```
